#!/bin/bash

if [ $# -ne 2 ]
then
    echo 'Usage:' 1>&2
    echo '  create "Full Name" full.name@domain' 1>&2
    exit 1
fi

name="$1"
email="$2"
ca=${VPN_CA:-.}
ca_cert=${VPN_CA_CERT:-.}

# Certificates valid for 2 years.
CERT_VALIDITY=710

# Temporary files.
KEY_FILE=${ca}/key.user$$
REQ_FILE=${ca}/req.user$$

# Output files.
CERT_FILE=${ca}/cert.user$$
PKG_FILE=${ca}/pkg.user$$

# Create private key.
echo '**** Generate private key...' 1>&2
./create-key > ${KEY_FILE}
if [ $? -ne 0 ]
then
    echo Private key generation failed. 1>&2
    exit 1
fi


# Create certificate request.
# Note: the certificate contains a DNS SubjectAltName which is device name
# with .device.local appended.  This is not expected to be a real DNS name.
echo '**** Generate certificate request...' 1>&2
suffix=device.local
./create-cert-request -k ${KEY_FILE} -U 'VPN user' -O 'Trust Networks' \
    -N "${name}" -E "${email}" --hosts "${name}.${suffix}" > ${REQ_FILE}
if [ $? -ne 0 ]
then
    echo Certificate request creation failed. 1>&2
    exit 1
fi

echo '**** Signing request...' 1>&2
# Sign certificate request to create certificate.
./create-cert -r ${REQ_FILE} -k ${ca_cert}/key.ca -c ${ca_cert}/cert.ca \
    -v ${CERT_VALIDITY} -C > ${CERT_FILE}
if [ $? -ne 0 ]
then
    echo Certificate signing failed. 1>&2
    exit 1
fi

# Delete request.
rm -f ${REQ_FILE}

# Verify.
echo '**** Verify certificate...' 1>&2
openssl verify -CAfile ${ca_cert}/cert.ca ${CERT_FILE} 1>&2
if [ $? -ne 0 ]
then
    echo Certificate verification failed. 1>&2
    exit 1
fi

# Output OpenVPN config for the client.
(
    cat client.conf
    echo '<ca>'
    cat ${ca_cert}/cert.ca
    echo '</ca>'
    echo '<cert>'
    cat ${CERT_FILE}
    echo '</cert>'
    echo '<key>'
    cat ${KEY_FILE}
    echo '</key>'
    echo '<tls-auth>'
    cat ${ca_cert}/ta.key
    echo '</tls-auth>'
) > ${PKG_FILE}

(
    openssl x509 -in ${CERT_FILE}  -noout -serial -email -subject -dates
    echo '----'
) >> ${ca}/register

# Remove stuff not needed.
rm -f ${KEY_FILE}

# This leaves the certificate and the package.  Now, rename them.

# Get certificate serial.
serial=$(openssl x509 -in ${CERT_FILE} -noout -serial | sed 's/serial=//')

mv ${CERT_FILE} ${ca}/cert.${serial}
CERT_FILE=${ca}/cert.${serial}

mv ${PKG_FILE} ${ca}/pkg.${serial}.ovpn
PKG_FILE=${ca}/pkg.${serial}.ovpn

echo '**** All complete.' 1>&2

echo VPN configuration file is: ${PKG_FILE} 1>&2
echo ${PKG_FILE}



